[package]
name = "slaist"
version = "0.1.0"
edition = "2024"
default-run = "slaist"

[dependencies]
tokio = { workspace = true }
todoist = { path = "../todoist" }
chrono = { version = "0.4", features = ["serde"] }
